### ISSUE TITLE
i am an idiot

### ISSUE THREAD

**Issue by MichalAsik** [GeorgeSikora/MultiplayerGame#1]
How to run that multiplayer game 👍

**Comment by GeorgeSikora** [comment]
Just download the Xampp software, that runs Apache web server, and start it up, make sure you copied the htdocs to an "C:/Xampp/htdocs/..." folder, just replace this folder instead of the  previous one. Next what you need to do, move the folder "server" to some folder, where you know the path, you can also grab it to the main "C:/server/..." and after that been done, just start CMD, go to the "server" folder, and run command "node server.js", server will start. you must have node.js downloaded yet. And thats it.
